apiVersion: v1
kind: Pod
metadata:
  name: ember-rails-app
  labels:
    name: ember-rails-app
    app: demo
spec:
  containers:
  - name: ember-rails-app
    image: sdadlani311/ember-rails-app:$BUILD_ID
    ports:
    - containerPort: 80
      protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: mycache
  labels:
    name: mycache
    app: demo
spec:
  containers:
  - name: mycache
    image: redis:alpine
    ports:
    - containerPort: 6379
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ember-rails-app
  labels:
    name: ember-rails-app
    app: demo
spec:
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: ember-rails-app
    app: demo
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mycache
  labels:
    name: mycache
    app: demo
spec:
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
      protocol: TCP
  selector:
    name: mycache
    app: demo
  type: NodePort
